version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: greenweez data source
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of Greenweez / we have one row per productid found in each orders id
        columns:
          - name: date date
            description: the date of purchase
          - name: orders id
            description: foreign key to ship
          - name: pdt_id
            description: foreign key to product
          - name: revenue
            description: the amount paid by the customer to purchase the product. revenue = quantity * selling price
          - name: quantity
            description: the quantity of products purchased for this order
        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"
    
         
      - name: product
        identifier: raw_gz_product 
        description: product data of greenweez
        columns:
          - name: products_id
            description: primary key of the table
          - name: purchase price
            description: the purchase price of the product
              
              
      - name: ship
        identifier: raw_gz_ship
        description: shiping info data of greenweez / orders id is the prmary key
        columns:
          - name: orders id
            description: primary key of the table
          - name: shipping fee
            description: the price the customer pays for shipping
          - name: log cost
            description: the cost of preparing the parcel in the warehouse
          - name: ship cost
            description: the shippina cost paid bv Greenweez to the carrier/transporter
      - name: adwords
        identifier: raw_gz_adwords
        description: campaign of adwords and costs of ads and clicks
        columns:
          - name: date_date 
            description: date of adwords campaign
          - name: paid_source
            description: source of payment 
          - name: campaign_key
            description: key of the campigns
          - name: camPGN_name
            description: name of the campaigns includes product name, country   
          - name: ads_cost
            description: cost per ad   
          - name: impression
            description: count of impressions of campaign
          - name: click
            description: count of clicks
        tests:
          - unique:
              column_name: "(date_date || '-' || campaign_key)"
      - name: bing
        identifier: raw_gz_bing
        description: campaign of bing and costs of ads and clicks
        columns:
          - name: date_date 
            description: date of bing campaign
          - name: paid_source
            description: source of payment 
          - name: campaign_key
            description: key of the campigns
          - name: camPGN_name
            description: name of the campaigns includes product name, country   
          - name: ads_cost
            description: cost per ad   
          - name: impression
            description: count of impressions of campaign
          - name: click
            description: count of clicks
        tests:
          - unique:
              column_name: "(date_date || '-' || campaign_key)"
      - name: criteo
        identifier: raw_gz_criteo
        description: campaign of criteo and costs of ads and clicks
        columns:
          - name: date_date 
            description: date of criteo campaign
          - name: paid_source
            description: source of payment 
          - name: campaign_key
            description: key of the campigns
          - name: camPGN_name
            description: name of the campaigns same as campaign key  
          - name: ads_cost
            description: cost per ad   
          - name: impression
            description: count of impressions of campaign
          - name: click
            description: count of clicks 
        tests:
          - unique:
              column_name: "(date_date || '-' || campaign_key)"     
      - name: facebook
        identifier: raw_gz_facebook
        description: campaign of facebook and costs of ads and clicks
        columns:
          - name: date_date 
            description: date of criteo campaign
          - name: paid_source
            description: source of payment 
          - name: campaign_key
            description: key of the campigns
          - name: camPGN_name
            description: name of the campaigns including type of campaign 
          - name: ads_cost
            description: cost per ad   
          - name: impression
            description: count of impressions of campaign
          - name: click
            description: count of clicks
        tests:
          - unique:
              column_name: "(date_date || '-' || campaign_key)"
models:
  - name: int_campaigns_day
    description: daily results of sum ads_cost, impression and clicks
    columns:
      - name: date_date
        description: daily results of values
        tests:
          - unique
      - name: ads_cost
        description: sum of daily costs
        tests:
          - not_null
      - name: ads_impression
        description: sum of daily impressions
        tests:
          - not_null
      - name: ads_clicks
        description: sum of daily clicks
        tests:
          - not_null    
              
             
         
