version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: greenweez data source
    tables:
      - name: sales
        identifier: raw_gz_sales
        tests:
          - not_null:
              column_name: "(pdt_id || '_' || orders_id)"
          - unique:
              column_name: "(pdt_id || '_' || orders_id)"
             
      - name: product
        identifier: raw_gz_product 
        description: product data of greenweez
        tests:
          - unique
          - not_null
              
              
      - name: ship
        identifier: raw_gz_ship
        description: shiping info data of greenweez / orders id is the prmary key
        tests:
          - unique
          - not_null
             
              
